USE [master]
GO

/****** Object:  Database [CarRentalDb]    Script Date: 19/04/2021 14:19:47 ******/
CREATE DATABASE [CarRentalDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarRentalDb', FILENAME = N'D:\sql server\sql server express 2019\MSSQL15.SQLEXPRESS\MSSQL\DATA\CarRentalDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CarRentalDb_log', FILENAME = N'D:\sql server\sql server express 2019\MSSQL15.SQLEXPRESS\MSSQL\DATA\CarRentalDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarRentalDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarRentalDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CarRentalDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CarRentalDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CarRentalDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CarRentalDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [CarRentalDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CarRentalDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarRentalDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarRentalDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarRentalDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CarRentalDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CarRentalDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarRentalDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CarRentalDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarRentalDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CarRentalDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarRentalDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarRentalDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarRentalDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarRentalDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarRentalDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CarRentalDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarRentalDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CarRentalDb] SET  MULTI_USER 
GO

ALTER DATABASE [CarRentalDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarRentalDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarRentalDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarRentalDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CarRentalDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CarRentalDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CarRentalDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CarRentalDb] SET  READ_WRITE 
GO

